const display=document.getElementById('display'), expression=document.getElementById('expression');
let expr='', justEvaluated=false, lastResult=null;
const historyKey='khanCalcHistory';
function render(){display.textContent=expr||'0';}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>t.style.display='none',1500)}
function sanitize(s){return s.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replace(/[^0-9+\-*/().%\s]/g,'')}
function calculateExpression(s){let x=s.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');x=sanitize(x);if(!x)return 0;if(!/^[0-9+\-*/().\s]+$/.test(x))throw Error();let v=Function('"use strict";return ('+x+')')();if(!Number.isFinite(v))throw Error();return Number(v.toPrecision(12));}
function add(v){if(justEvaluated && /[0-9.]/.test(v)){expr='';expression.textContent='';justEvaluated=false} if(v==='.') {let m=expr.split(/[+\-×÷()]/).pop();if(m.includes('.'))return;if(!m)m='0';} if(v==='('){if(expr && /[0-9)]$/.test(expr))expr+='×';} if(/[0-9]/.test(v)&&expr.endsWith(')'))expr+='×'; expr+=v;justEvaluated=false;render()}
function op(v){if(!expr){if(lastResult!==null)expr=String(lastResult);else return} if(justEvaluated)justEvaluated=false; if(/[+\-×÷]$/.test(expr))expr=expr.slice(0,-1)+v; else expr+=v;render()}
function clear(){expr='';lastResult=null;expression.textContent='';justEvaluated=false;render()}
function backspace(){if(justEvaluated){clear();return}expr=expr.slice(0,-1);render()}
function sign(){if(!expr)return;const m=expr.match(/(\d+(?:\.\d+)?)$/);if(m){const i=expr.length-m[1].length;expr=expr.slice(0,i)+(i>0&&expr[i-1]==='−'?'': '−')+m[1];render()}}
function paren(){let opens=(expr.match(/\(/g)||[]).length, closes=(expr.match(/\)/g)||[]).length;if(opens>closes && /[0-9)]$/.test(expr))expr+=')';else if(!expr||/[+\-×÷(]$/.test(expr))expr+='(';else expr+='×(';render()}
function percent(){const m=expr.match(/(\d+(?:\.\d+)?)$/);if(m){expr=expr.slice(0,expr.length-m[1].length)+m[1]+'%';render()}}
function equals(){if(!expr)return;try{const original=expr;const value=calculateExpression(expr);lastResult=value;expression.textContent=original+' =';display.textContent=String(value);expr=String(value);justEvaluated=true;saveHistory(original,value)}catch{display.textContent='Error';justEvaluated=true}}
function saveHistory(e,r){const h=JSON.parse(localStorage.getItem(historyKey)||'[]');h.unshift({e,r,t:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});localStorage.setItem(historyKey,JSON.stringify(h.slice(0,100)))}
function renderHistory(){const list=document.getElementById('historyList'),h=JSON.parse(localStorage.getItem(historyKey)||'[]');list.innerHTML=h.length?h.map(x=>`<div class="history-item"><div class="history-expr">${x.e}</div><div class="history-result">= ${x.r}</div><div class="history-time">${x.t}</div></div>`).join(''):'<p style="color:#999;text-align:center;padding:30px">No calculations yet.</p>'}
const units={Length:{Meter:1,Kilometer:1000,Centimeter:.01,Millimeter:.001,Foot:.3048,Inch:.0254,Mile:1609.344},Area:{"Square meter":1,"Square kilometer":1e6,"Square foot":.092903,"Square inch":.00064516,"Acre":4046.856},Volume:{Liter:1,"Milliliter":.001,"Cubic meter":1000,"Gallon":3.785411784},Weight:{Gram:1,Kilogram:1000,Milligram:.001,Pound:453.59237,Ounce:28.349523125},Temperature:{Celsius:'C',Fahrenheit:'F',Kelvin:'K'},Speed:{"m/s":1,"km/h":.277777778,"mph":.44704,"knot":.514444},Time:{Second:1,Minute:60,Hour:3600,Day:86400},Data:{Byte:1,KB:1024,MB:1048576,GB:1073741824},Energy:{Joule:1,"Kilojoule":1000,"Watt-hour":3600,"Kilowatt-hour":3600000},Pressure:{Pascal:1,"Kilopascal":1000,Bar:100000,PSI:6894.757},Angle:{Degree:1,Radian:57.295779513,Gradian:.9}};
let currentCat='Length';
function initConverter(){const cats=document.getElementById('categories');cats.innerHTML=Object.keys(units).map(k=>`<button class="cat-btn ${k==='Length'?'active':''}" data-cat="${k}">${k}</button>`).join('');cats.onclick=e=>{const b=e.target.closest('.cat-btn');if(!b)return;currentCat=b.dataset.cat;cats.querySelectorAll('.cat-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');fillUnits()};document.getElementById('fromValue').addEventListener('input',convert);document.getElementById('fromUnit').addEventListener('change',convert);document.getElementById('toUnit').addEventListener('change',convert);document.getElementById('swapBtn').onclick=()=>{const a=document.getElementById('fromUnit'),b=document.getElementById('toUnit'),v=document.getElementById('fromValue');[a.value,b.value]=[b.value,a.value];convert()};fillUnits()}
function fillUnits(){const arr=Object.keys(units[currentCat]);document.getElementById('converterTitle').textContent=currentCat;document.getElementById('fromUnit').innerHTML=arr.map(x=>`<option>${x}</option>`).join('');document.getElementById('toUnit').innerHTML=arr.map(x=>`<option>${x}</option>`).join('');if(arr[1])document.getElementById('toUnit').value=arr[1];convert()}
function convert(){const a=document.getElementById('fromValue'),b=document.getElementById('toValue'),fu=document.getElementById('fromUnit').value,tu=document.getElementById('toUnit').value;let v=Number(a.value)||0;if(currentCat==='Temperature'){let c=fu==='Celsius'?v:fu==='Fahrenheit'?(v-32)*5/9:v-273.15;let out=tu==='Celsius'?c:tu==='Fahrenheit'?c*9/5+32:c+273.15;b.value=Number(out.toPrecision(10))}else{const map=units[currentCat];b.value=Number((v*map[fu]/map[tu]).toPrecision(10))}}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(name+'View').classList.add('active');if(name==='history')renderHistory()}
document.querySelectorAll('.key').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action,v=b.dataset.value;if(a==='clear')clear();else if(a==='backspace')backspace();else if(a==='equals')equals();else if(a==='sign')sign();else if(a==='paren')paren();else if(a==='percent')percent();else if(/[+\-×÷]/.test(v||''))op(v);else if(v)add(v)}));
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>showView('calculator'));document.getElementById('portraitBtn').onclick=()=>showView('portrait');document.getElementById('clearHistory').onclick=()=>{localStorage.removeItem(historyKey);renderHistory()};document.getElementById('lockPortrait').onclick=async()=>{try{await screen.orientation.lock('portrait');toast('Portrait locked')}catch{toast('Portrait lock is not supported here')}};document.getElementById('unlockPortrait').onclick=async()=>{try{screen.orientation.unlock();toast('Portrait unlocked')}catch{toast('Portrait unlocked')}};document.getElementById('menuBtn').onclick=()=>toast('Khan Calculator');
initConverter();render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
